theme: jekyll-theme-cayman
title: Mariel's site
description: Welcome! Here you can find my projects, tutorials in the form of jupyter notebooks and some infos about me.
google_analytics: UA-107124463-1
